name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  multi-arch-build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64    # amd64
            distro: ubuntu_latest
          - arch: aarch64   # arm64
            distro: ubuntu_latest
          - arch: armv7     # armhf
            distro: ubuntu_latest
          - arch: armv6     # armel
            distro: bullseye
          - arch: i386      # i386
            distro: ubuntu_latest
          - arch: ppc64le   # ppc64el
            distro: ubuntu_latest
          - arch: riscv64   # riscv64
            distro: ubuntu_latest

    steps:
      - uses: actions/checkout@v4

      - name: Run on architecture
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${{ github.workspace }}:/workspace"
          run: |
            apt-get update
            sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
            if [ -f /etc/apt/sources.list.d/ubuntu.sources ]; then
              sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
            fi
            apt-get update
            apt-get build-dep -y partclone
            apt-get install -y f2fs-tools hfsprogs exfatprogs gddrescue reiser4progs libxxhash-dev libisal-dev build-essential autoconf automake gettext git
            cd /workspace
            ./autogen
            ./configure --enable-fs-test --enable-feature-test --enable-extfs --enable-ntfs --enable-fat --enable-exfat --enable-hfsp --enable-apfs --enable-btrfs --enable-minix --enable-f2fs --enable-reiser4 --enable-xfs
            make
            make check
